apps/quiz/urls.py
from django.urls import path

from .views import home

app_name = 'quiz'
urlpatterns = [
    path('', home),
]

apps/user_profile/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView, LogoutView

app_name = 'user_profile'
urlpatterns = [
	# Class method as path takes view.method
	# Passing kwargs used for multiple change.. see the import class in github link
	# https://github.com/django/django/blob/master/django/contrib/auth/views.py
	# path('login/', LoginView.as_view( **{'template_name': 'login.html'})),
	path('login/', LoginView.as_view(template_name='login.html'), name='login'),
	path('logout/', LogoutView.as_view(), name='logout'),
]

learning_platform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.quiz.urls', namespace='quiz')),
    path('', include('apps.user_profile.urls', namespace='user_profile')),
]

apps/quiz/models.py
from django.db import models
from django.utils.text import slugify

# from django.utils.translation import gettext_lazy as _
# See this translation module


class Category(models.Model):
	name = models.CharField(max_length=40, unique=True)
	slug = models.SlugField(blank=True, unique=True)
	# Takes date and time from the system in the database and it can't be updated 
	created = models.DateTimeField(auto_now_add=True)
	# On each update time can be changed
	updated = models.DateTimeField(auto_now=True)
	is_active = models.BooleanField(default=False)

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.name)
		super().save(*args, **kwargs)

	def __str__(self):
		# return _(self.name)
		return self.name

apps/user_profile/models.py
from django.db import models
from django.contrib.auth.models import User

from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
	# user = models.OneToOneField(User, on_delete=models.CASCADE)
	# Bottom one is bad practice
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
	# Now put all these as null
	mobile = models.CharField(max_length=15, null=True, blank=True)
	address = models.CharField(max_length=30, null=True, blank=True)

	def __str__(self):
		return '{} {}'.format(self.user.username, self.mobile)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()
    

apps/quiz/views.py
from django.shortcuts import render

from pprint import pprint
import numpy as np

from .models import Category

# function based views
def home(request):
	# View what request offers
	#pprint(request.__dict__)
	template = 'home.html'
	context ={
		# "username": "Sunil",
		'title': 'Home Page',
		'data': Category.objects.all(),
		# 'numpyData': np.zeros(5),
	}
	# render(request, template, context=should be dict)
	return render(request, template, context=context)

apps/user_profile/views.py
from django.shortcuts import render

# Create your views here.

apps/quiz/templates/home.html
{% extends 'base.html' %}
{% block title %}
	{{ title }}
{% endblock title%}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock navbar %}

{% block body %}
	<h2>
		<!-- Template filters are used by "variableName | filer" -->
		{% if request.user.is_authenticated %}
			Welcome {{ request.user | capfirst }}!
			<a href="{% url 'user_profile:logout' %}">Logout</a>
		{% else %}
			<!-- url namespace:name namespace define in settings and urls page, name define in urls page  -->
			Welcome Learning Platform
			<a href="{% url 'user_profile:login' %}">Login</a>
		{% endif %}
	</h2>
	<h3>
		{% for obj in data %}
			{{ forloop.counter }}. {{ obj.name }}<br>
			
			{% empty %}
				<h4>No Data to Show</h4>
		{% endfor %}
	</h3>
	<h4>
		{% for i in numpyData %}
			{{ i }}
		{% endfor %}
	</h4>
{% endblock body %}

apps/user_profile/templates/login.html
{% extends 'base.html' %}
{% block title %}
Login Page
{% endblock title %}

{% block body %}
    <h1><center>Login Page</center></h1>
    <!-- as_p means display form as paragraph -->
    <form method="POST">
        {% csrf_token %}
        <center>
            <h1>{{ form.as_p }}</h1> 
            <input type="submit" name="" value="Login">
        </center>
    </form>
{% endblock body %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>
        {% block title %} 
            Learning Platform
        {% endblock title%}
    </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <style>
  .fakeimg {
      height: 200px;
      background: #aaa;
  }
  </style>
</head>
<body>
    {% block navbar %}
    {% endblock navbar %}
    <div class="container" style="margin-top:30px">
      <div class="row">
        <div class="col-sm-8">
            {% block body %} 
            {% endblock body%}
        </div>
      </div>
    </div>

    <div class="jumbotron text-center" style="margin-bottom:0">
      <p>Footer</p>
    </div>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>    
        </ul>
      </div>  
    </nav>